services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: make_the_pick
      POSTGRES_PASSWORD: make_the_pick
      POSTGRES_DB: make_the_pick
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
