services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: draftr
      POSTGRES_PASSWORD: draftr
      POSTGRES_DB: draftr
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
